### ISSUE TITLE
Select apps to re-enable every now and then (suggestion)

### ISSUE THREAD

**Issue by flindeberg** [Jolanrensen/PermanentProxy-for-WearOS#14]
I do not know the feasibility of this, but often (weekly or so) the proxy breaks (perhaps connected to IPv4?) and geo-blocked apps become disabled. Often a simple "enable" in the Play Store solves this and they are up and running again. 

Would it be possible to have `PermanentProxy` to re-enable a specified set of apps (if they are disabled) every hour or so? Or just a hard-coded Google Pay? :-)

`adb shell pm enable com.google.android.gms` might do it for Google Pay, I haven't checked yet, I'll update the issue later.

**Comment by Jolanrensen** [comment]
If the proxy is set up correctly, the watch should enable Google pay automatically after a while. I found this out myself by travelling to France and after a day or so Google pay appeared because I was connected to French internet.
This works the same with a proxy, so if you stay connected to your proxy it will reappear eventually!
You can also tell the watch to "check again" by setting the IP/port again in the Permanent Proxy app or by tapping the "Home version" in the system versions.
If Google pay doesn't reappear automatically, something might not be set up right or like you said, there might be something up with the network that informs Google pay of your country (my guess is IPv6 on wifi).
You shouldn't have to enable Google pay manually, but if you do want to do that, I recommend the "Pay enabler" app, which opens the Google pay page on the play store, where you can hit "enable".

**Comment by flindeberg** [comment]
> If Google pay doesn't reappear automatically, something might not be set up right or like you said, there might be something up with the network that informs Google pay of your country (my guess is IPv6 on wifi).

After playing around a bit I found two scenarios; 

- the one connected to PermanentProxy was as you mention above, IPv6 over wifi. Solved by disabling wifi.
- the other was on the proxy(-server) side. Since passwords aren't allowed my proxy became public knowledge and was flooded within days (out-of-memory errors on the server) which obviously flunked PermanentProxy. Solved by using obscure port. 

It is out of scope for this project, but maybe put a mention somewhere that all IPv4s are regularly scanned so do not use a passwordless proxy on a default port?
